name: Generate Data Element Profiles

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
  
      - run: |
          pip install setuptools
          pip install jsonschema
          pip install pyyaml
          pip install .
          sudo apt install gettext
          cd deplane
          cp ENG_2_Colour.docx /opt/hostedtoolcache/Python/3.13.5/x64/lib/python3.13/site-packages/deplane/ENG_2_Colour.docx
          cd ..
          cd dep
          echo "Generating Data Element Profiles"
          echo "Use of Administrative Aircraft"
          deplane en https://open.canada.ca/data/recombinant-schema/adminaircraft.json adminaircraft-en.docx
          ls -la
          cd ..
          git status
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add dep
          git commit -m "Generating DEPs"
          git push -f origin master
